version: "3"

tasks:
  create-database-docker-instance:
    cmds:
      - 'docker run -e "ACCEPT_EULA=Y" -e "MSSQL_SA_PASSWORD=YourStrong@Passw0rd" -p 1433:1433 --name sql1 -d mcr.microsoft.com/mssql/server'
  install-migration-tools:
    cmds:
      - 'dotnet tool install --global dotnet-ef'
  create-migration:
    cmds:
      - 'dotnet ef migrations add FirstMigration --project "./src/App.DataLayer/App.DataLayer.csproj" --startup-project "./src/App.Api/App.Api.csproj"'
  list-migrations:
    cmds:
      - 'dotnet ef migrations list --project "./src/App.DataLayer/App.DataLayer.csproj" --startup-project "./src/App.Api/App.Api.csproj"'
  remove-migration:
    cmds:
      - 'dotnet ef migrations remove FirstMigration --project "./src/App.DataLayer/App.DataLayer.csproj" --startup-project "./src/App.Api/App.Api.csproj"'
  apply-migration:
    cmds:
      - 'dotnet ef database update FirstMigration --project "./src/App.DataLayer/App.DataLayer.csproj" --startup-project "./src/App.Api/App.Api.csproj"'
       